### ISSUE TITLE
Not able to use "us-central1" with Chirp

### ISSUE THREAD

**Issue by sureshpalemoni** [googleapis/python-speech#543]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-speech/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version:
  - Python version: 3.10
  - pip version: gcloud functions pip
  - `google-cloud-speech` version: `pip show google-cloud-speech`

#### Steps to reproduce

  1. Running the code on google cloud functions
  2. Use Chirp Model and location in recognizer as "us-central1"
  3. Name="projects/project-0/locations/us-central1/recognizers/_"

#### Code example

```python

    name = "projects/project-0/locations/us-central1/recognizers/_"

    request = cloud_speech.BatchRecognizeRequest(
        recognizer=name, config=config, files=files, recognition_output_config=output_config
    )

    operation = client.batch_recognize(request=request)
    response = operation.result()
```

#### Stack trace
```
textPayload: "Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/functions_framework/__init__.py", line 174, in view_func
    function(event)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/functions_framework/__init__.py", line 70, in wrapper
    return func(*args, **kwargs)
  File "/workspace/main.py", line 63, in speech2text
    response = speech_to_text(ffname, uid)
  File "/workspace/main.py", line 47, in speech_to_text
    operation = client.batch_recognize(request=request)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/google/cloud/speech_v2/services/speech/client.py", line 1808, in batch_recognize
    response = rpc(
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 113, in __call__
    return wrapped_func(*args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 74, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.InvalidArgument: 400 Expected resource location to be global, but found us-central1 in resource name."
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by parthea** [comment]
I'm going to transfer this issue to `google-cloud-python` as we're planning to move the code for `google-cloud-speech` there in the next 1-2 weeks
