### ISSUE TITLE
google.api_core.exceptions.Unknown: None Exception iterating requests! 

### ISSUE THREAD

**Issue by devinay** [googleapis/python-speech#77]
#### Environment details

  - OS type and version:  MacOS catalina 10.15.7
  - Python version: Python 3.8.5
  - pip version: pip 20.2.3
  - `google-cloud-speech` version: `Name: google-cloud-speech

> Version: 1.3.2
> Summary: Google Cloud Speech API client library
> Home-page: https://github.com/googleapis/python-speech
> Author: Google LLC
> Author-email: googleapis-packages@google.com
> License: Apache 2.0
> 

#### Steps to reproduce

  1. Followed the instructions [here] (https://github.com/googleapis/python-speech/tree/master/samples/microphone#setup) 
  2. Created a service account json key, set up the env path and also did gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
3. Ran `python transcribe_streaming_mic.py` and got this trace:
```
21:38 $ python transcribe_streaming_mic.py
Traceback (most recent call last):
  File "transcribe_streaming_mic.py", line 197, in <module>
    main()
  File "transcribe_streaming_mic.py", line 177, in main
    streaming_config = speech.StreamingRecognitionConfig(
AttributeError: module 'google.cloud.speech' has no attribute 'StreamingRecognitionConfig'
```
4. Made these changes:
```python
    config = speech.types.RecognitionConfig(
        encoding=speech.enums.RecognitionConfig.AudioEncoding.LINEAR16,
        sample_rate_hertz=RATE,
        language_code=language_code,
    )
    streaming_config = speech.types.StreamingRecognitionConfig(
        config=config, interim_results=True
    )
```
It was originally like this
```python
    client = speech.SpeechClient()
    config = speech.RecognitionConfig(
        encoding=speech.RecognitionConfig.AudioEncoding.LINEAR16,
        sample_rate_hertz=RATE,
        language_code=language_code,
    )
    streaming_config = speech.StreamingRecognitionConfig(
        config=config, interim_results=True
    )
```
5. The code throws a completely new exception :
```
21:39 $ python transcribe_streaming_mic.py
Traceback (most recent call last):
  File "/Users/veswara/gcp_priv_voice_key/env/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 150, in error_remapped_callable
    return _StreamingResponseIterator(result, prefetch_first_result=prefetch_first)
  File "/Users/veswara/gcp_priv_voice_key/env/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 73, in __init__
    self._stored_first_result = six.next(self._wrapped)
  File "/Users/veswara/gcp_priv_voice_key/env/lib/python3.8/site-packages/grpc/_channel.py", line 416, in __next__
    return self._next()
  File "/Users/veswara/gcp_priv_voice_key/env/lib/python3.8/site-packages/grpc/_channel.py", line 706, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception iterating requests!"
	debug_error_string = "None"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "transcribe_streaming_mic.py", line 197, in <module>
    main()
  File "transcribe_streaming_mic.py", line 188, in main
    responses = client.streaming_recognize(
  File "/Users/veswara/gcp_priv_voice_key/env/lib/python3.8/site-packages/google/cloud/speech_v1/helpers.py", line 80, in streaming_recognize
    return super(SpeechHelpers, self).streaming_recognize(
  File "/Users/veswara/gcp_priv_voice_key/env/lib/python3.8/site-packages/google/cloud/speech_v1/gapic/speech_client.py", line 410, in streaming_recognize
    return self._inner_api_calls["streaming_recognize"](
  File "/Users/veswara/gcp_priv_voice_key/env/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/Users/veswara/gcp_priv_voice_key/env/lib/python3.8/site-packages/google/api_core/retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "/Users/veswara/gcp_priv_voice_key/env/lib/python3.8/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/Users/veswara/gcp_priv_voice_key/env/lib/python3.8/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/Users/veswara/gcp_priv_voice_key/env/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 152, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.Unknown: None Exception iterating requests!
```

What could I be doing wrong ? 

Regards,
Vinay

**Comment by b-loved-dreamer** [comment]
Hi @devinay, I believe you're using the sample that relies on the newest version of the google-cloud-speech which is 2.0.0. You might be able to clear this issue by updating to 2.0.0 and migrating your code following this [guide](https://github.com/googleapis/python-speech/blob/master/UPGRADING.md) or, if you decide to stay with 1.3.2, looking into this #66. Please note that we're currently updating our samples to reflect all changes in the latest API.

**Comment by b-loved-dreamer** [comment]
Hi @devinay the sample has been updated to google-cloud-speech 2.0.0. The sample has been modified to support changes in the latest version of the API. Please let us know If you continue to experience issues.

**Comment by b-loved-dreamer** [comment]
Fixed. Please check updated sample.
