### ISSUE TITLE
ValueError: Protocol message FieldDescriptorProto has no "proto3_optional" field.

### ISSUE THREAD

**Issue by MikeS-nth** [googleapis/python-speech#81]
Getting an error when trying to import the Google Speech library:
ValueError: Protocol message FieldDescriptorProto has no "proto3_optional" field.

I Googled this extensively and did not find any solutions.

#### Environment details

  - OS type and version: MacOS 10.15.7 
  - Conda version: 4.8.3
  - Python version: 3.7.6
  - pip version: 20.2.2
  - google-cloud-speech version: 2.0.0
  - proto-plus version: 1.11.0

#### Steps to reproduce

  1. Install the library: `pip install google-cloud-speech`
  2. Attempt to import the library: `from google.cloud import speech`

#### Code example

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from google.cloud import speech
```

#### Stack trace
```
Traceback (most recent call last):

  File "<ipython-input-1-589439c37498>", line 1, in <module>
    from google.cloud import speech

  File "/Users/msanders/opt/anaconda3/envs/workenv/lib/python3.7/site-packages/google/cloud/speech/__init__.py", line 18, in <module>
    from google.cloud.speech_v1.services.speech.async_client import SpeechAsyncClient

  File "/Users/msanders/opt/anaconda3/envs/workenv/lib/python3.7/site-packages/google/cloud/speech_v1/__init__.py", line 18, in <module>
    from .services.speech import SpeechClient

  File "/Users/msanders/opt/anaconda3/envs/workenv/lib/python3.7/site-packages/google/cloud/speech_v1/services/speech/__init__.py", line 18, in <module>
    from .client import SpeechClient

  File "/Users/msanders/opt/anaconda3/envs/workenv/lib/python3.7/site-packages/google/cloud/speech_v1/services/speech/client.py", line 47, in <module>
    from google.cloud.speech_v1.types import cloud_speech

  File "/Users/msanders/opt/anaconda3/envs/workenv/lib/python3.7/site-packages/google/cloud/speech_v1/types/__init__.py", line 18, in <module>
    from .cloud_speech import (

  File "/Users/msanders/opt/anaconda3/envs/workenv/lib/python3.7/site-packages/google/cloud/speech_v1/types/cloud_speech.py", line 50, in <module>
    class RecognizeRequest(proto.Message):

  File "/Users/msanders/opt/anaconda3/envs/workenv/lib/python3.7/site-packages/proto/message.py", line 215, in __new__
    field=[i.descriptor for i in fields],

  File "/Users/msanders/opt/anaconda3/envs/workenv/lib/python3.7/site-packages/proto/message.py", line 215, in <listcomp>
    field=[i.descriptor for i in fields],

  File "/Users/msanders/opt/anaconda3/envs/workenv/lib/python3.7/site-packages/proto/fields.py", line 111, in descriptor
    proto3_optional=self.optional,

ValueError: Protocol message FieldDescriptorProto has no "proto3_optional" field.
```

**Comment by b-loved-dreamer** [comment]
Hi @MikeS-nth, I followed the steps and was unable to reproduce this error. I was able to install the library and use the service with no issues. Please let us know if there's any other implementation detail you have included locally.

**Comment by MikeS-nth** [comment]
Hi @b-loved-dreamer  -- thanks for investigating.  I dug a little further, and it looks like it was a dependency issue with protobuf, not proto-plus.

In case anyone else encounters this issue, it was fixed by running `pip install protobuf --upgrade` 
(Note, updating protobuf via conda failed, at least in my environment.)

**Comment by b-loved-dreamer** [comment]
I am glad you got it figured out. Thanks for the information.
